CREATE TABLE `Jutsu` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `effects` json NOT NULL,
  `target` enum('SELF','OTHER_USER','OPPONENT','ALLY','CHARACTER','GROUND','EMPTY_GROUND') COLLATE utf8mb4_unicode_ci NOT NULL,
  `range` int NOT NULL,
  `cooldown` int NOT NULL DEFAULT '0',
  `bloodlineId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requiredRank` enum('STUDENT','GENIN','CHUNIN','JONIN','COMMANDER','ELDER','NONE') COLLATE utf8mb4_unicode_ci NOT NULL,
  `jutsuType` enum('NORMAL','SPECIAL','BLOODLINE','FORBIDDEN','LOYALTY','CLAN','EVENT','AI') COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `jutsuWeapon` enum('STAFF','AXE','FIST_WEAPON','SHURIKEN','SICKLE','DAGGER','SWORD','POLEARM','FLAIL','CHAIN','FAN','BOW','HAMMER','NONE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `battleDescription` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `chakraCostPerc` double NOT NULL DEFAULT '0.05',
  `healthCostPerc` double NOT NULL DEFAULT '0',
  `jutsuRank` enum('D','C','B','A','S') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'D',
  `staminaCostPerc` double NOT NULL DEFAULT '0.05',
  `villageId` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `method` enum('SINGLE','ALL','AOE_CIRCLE_SPAWN','AOE_LINE_SHOOT','AOE_CIRCLE_SHOOT','AOE_SPIRAL_SHOOT') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'SINGLE',
  `actionCostPerc` double NOT NULL DEFAULT '80',
  `hidden` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `Jutsu_name_key` (`name`),
  UNIQUE KEY `Jutsu_image_key` (`image`),
  KEY `Jutsu_bloodlineId_idx` (`bloodlineId`),
  KEY `Jutsu_villageId_idx` (`villageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
