CREATE TABLE `Item` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `effects` json NOT NULL,
  `itemType` enum('WEAPON','CONSUMABLE','ARMOR','ACCESSORY','MATERIAL','EVENT','OTHER') COLLATE utf8mb4_unicode_ci NOT NULL,
  `rarity` enum('COMMON','RARE','EPIC','LEGENDARY') COLLATE utf8mb4_unicode_ci NOT NULL,
  `slot` enum('HEAD','CHEST','LEGS','FEET','HAND','ITEM','NONE') COLLATE utf8mb4_unicode_ci NOT NULL,
  `cost` int NOT NULL DEFAULT '1',
  `weaponType` enum('STAFF','AXE','FIST_WEAPON','SHURIKEN','SICKLE','DAGGER','SWORD','POLEARM','FLAIL','CHAIN','FAN','BOW','HAMMER','NONE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `canStack` tinyint(1) NOT NULL DEFAULT '0',
  `stackSize` int NOT NULL DEFAULT '1',
  `target` enum('SELF','OTHER_USER','OPPONENT','ALLY','CHARACTER','GROUND','EMPTY_GROUND') COLLATE utf8mb4_unicode_ci NOT NULL,
  `chakraCostPerc` double NOT NULL DEFAULT '0',
  `image` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `staminaCostPerc` double NOT NULL DEFAULT '0',
  `destroyOnUse` tinyint(1) NOT NULL DEFAULT '0',
  `range` int NOT NULL DEFAULT '0',
  `method` enum('SINGLE','ALL','AOE_CIRCLE_SPAWN','AOE_LINE_SHOOT','AOE_CIRCLE_SHOOT','AOE_SPIRAL_SHOOT') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'SINGLE',
  `actionCostPerc` double NOT NULL DEFAULT '60',
  `healthCostPerc` double NOT NULL DEFAULT '0',
  `battleDescription` text COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (_utf8mb4''),
  `hidden` tinyint NOT NULL DEFAULT '0',
  `cooldown` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `Item_name_key` (`name`),
  UNIQUE KEY `Item_image_key` (`image`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
