import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
// import Script from "next/script";

const Header: React.FC = () => {
  const router = useRouter();
  const imageId = (router.query.imageid as string) ?? "";
  return (
    <>
      <Head>
        <title>The Ninja-RPG.com - a free browser based mmorpg</title>
        <meta
          name="description"
          content="A free browser based online game set in the ninja world of the Seichi!"
        />
        <meta
          name="keywords"
          content="mmorpg, online, rpg, game, anime, manga, strategy, multiplayer, ninja, community, core 3, theninja-rpg"
        />
        <meta name="distribution" content="Global" />
        <meta name="copyright" content="TheNinja-RPG.com" />
        <meta name="revisit-after" content="1 day" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />

        {/* Social Media Sharing */}
        <meta property="og:url" content="https://www.theninja-rpg.com" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="TheNinja-RPG" />
        <meta
          property="og:description"
          content="A free browser based online game set in the ninja world of the Seichi"
        />
        <meta
          property="og:image"
          content={`https://www.theninja-rpg.com/api/og?imageid=${imageId}`}
        />
        <meta name="twitter:card" content="concept art generated by AI" />
        <meta name="twitter:image:alt" content="TheNinja-RPG Concept Art" />
        <meta
          name="twitter:title"
          content="The Ninja-RPG.com - a free browser based mmorpg"
        />
        <meta
          name="twitter:description"
          content="A free browser based online game set in the ninja world of the Seichi"
        />
        <meta
          name="twitter:image"
          content={`https://www.theninja-rpg.com/api/og?imageid=${imageId}`}
        />
      </Head>
      {/* 
      NOT USED FOR NOW. NOTE THAT THERE MAY BE CORS CONFLICS CAUSED BETWEEN HIGHLIGHT.IO AND GOOGLE TAG MANAGER
      <Script id="google-tag-manager" strategy="afterInteractive">
        {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5TK3T9');`}
      </Script> */}
    </>
  );
};

export default Header;
