import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

const Header: React.FC = () => {
  const router = useRouter();
  const imageId = (router.query.imageid as string) ?? "";
  return (
    <Head>
      <title>The Ninja-RPG.com - a free browser based mmorpg</title>
      <meta
        name="description"
        content="A free browser based online game set in the ninja world of the Seichi!"
      />
      <meta
        name="keywords"
        content="mmorpg, online, rpg, game, anime, manga, strategy, multiplayer, ninja, community, core 3, theninja-rpg"
      />
      <meta name="distribution" content="Global" />
      <meta name="copyright" content="TheNinja-RPG.com" />
      <meta name="revisit-after" content="1 day" />
      <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
      <link rel="icon" href="/favicon.ico" />

      {/* Social Media Sharing */}
      <meta property="og:url" content="https://www.theninja-rpg.com"></meta>
      <meta property="og:type" content="website"></meta>
      <meta property="og:title" content="TheNinja-RPG"></meta>
      <meta
        property="og:description"
        content="A free browser based online game set in the ninja world of the Seichi"
      ></meta>
      <meta
        property="og:image"
        content={`https://www.theninja-rpg.com/api/og?imageid=${imageId}`}
      ></meta>
      <meta name="twitter:card" content="concept art generated by AI"></meta>
      <meta name="twitter:image:alt" content="TheNinja-RPG Concept Art"></meta>
      <meta
        name="twitter:title"
        content="The Ninja-RPG.com - a free browser based mmorpg"
      ></meta>
      <meta
        name="twitter:description"
        content="A free browser based online game set in the ninja world of the Seichi"
      ></meta>
      <meta
        name="twitter:image"
        content={`https://www.theninja-rpg.com/api/og?imageid=${imageId}`}
      ></meta>
    </Head>
  );
};

export default Header;
