ALTER TABLE `VillageStructure` ADD `anbuSquadsPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `arenaRewardPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `bankInterestPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `blackMarketDiscountPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `clansPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `hospitalSpeedupPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `itemDiscountPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `patrolsPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `ramenDiscountPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `regenIncrease` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `sleepRegenPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `structureDiscountPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `trainSpeedPerLvl` tinyint DEFAULT 0 NOT NULL;
ALTER TABLE `VillageStructure` ADD `villageDefencePerLvl` tinyint DEFAULT 0 NOT NULL;

UPDATE VillageStructure SET sleepRegenPerLvl = 2 WHERE VillageStructure.name = "Home";
UPDATE VillageStructure SET trainSpeedPerLvl = 1 WHERE VillageStructure.name = "Training Grounds";
UPDATE VillageStructure SET clansPerLvl = 1, villageDefencePerLvl = 1 WHERE VillageStructure.name = "Clan Hall";
UPDATE VillageStructure SET structureDiscountPerLvl = 1 WHERE VillageStructure.name = "Town Hall";
UPDATE VillageStructure SET arenaRewardPerLvl = 5 WHERE VillageStructure.name = "Battle Arena";
UPDATE VillageStructure SET regenIncreasePerLvl = 1 WHERE VillageStructure.name = "Mission Hall";
UPDATE VillageStructure SET bankInterestPerLvl = 1 WHERE VillageStructure.name = "Bank";
UPDATE VillageStructure SET itemDiscountPerLvl = 5 WHERE VillageStructure.name = "Item shop";
UPDATE VillageStructure SET hospitalSpeedupPerLvl = 2 WHERE VillageStructure.name = "Hospital";
UPDATE VillageStructure SET anbuSquadsPerLvl = 1, villageDefencePerLvl = 1 WHERE VillageStructure.name = "ANBU";
UPDATE VillageStructure SET ramenDiscountPerLvl = 5 WHERE VillageStructure.name = "Ramen Shop";
UPDATE VillageStructure SET blackDiscountPerLvl = 5 WHERE VillageStructure.name = "Black Market";
UPDATE VillageStructure SET villageDefencePerLvl = 2, patrolsPerLvl = 1 WHERE VillageStructure.name = "Protectors";
UPDATE VillageStructure SET villageDefencePerLvl = 5 WHERE VillageStructure.name = "Walls";