ALTER TABLE `PaypalTransaction` MODIFY COLUMN `createdById` varchar(191);
ALTER TABLE `PaypalTransaction` MODIFY COLUMN `affectedUserId` varchar(191);
ALTER TABLE `UserReport` MODIFY COLUMN `status` enum('UNVIEWED','REPORT_CLEARED','BAN_ACTIVATED','SILENCE_ACTIVATED','BAN_ESCALATED','SILENCE_ESCALATED','OFFICIAL_WARNING') NOT NULL DEFAULT 'UNVIEWED';
ALTER TABLE `UserReportComment` MODIFY COLUMN `decision` enum('UNVIEWED','REPORT_CLEARED','BAN_ACTIVATED','SILENCE_ACTIVATED','BAN_ESCALATED','SILENCE_ESCALATED','OFFICIAL_WARNING');