TRUNCATE Battle;
TRUNCATE BattleAction;
TRUNCATE BattleHistory;
TRUNCATE DataBattleAction;
UPDATE UserData SET maxHealth=50+50*level, maxChakra=50+50*level, maxStamina=50+50*level, immunityUntil='2024-03-11 12:00:35.000';
UPDATE UserData a SET a.battleId=NULL, a.status="AWAKE", a.travelFinishAt=NULL WHERE NOT EXISTS (SELECT id FROM Battle b WHERE b.id = a.battleId) AND a.battleId IS NOT NULL;

ALTER TABLE `Battle` MODIFY COLUMN `battleType` enum('ARENA','COMBAT','SPARRING','KAGE_AI','KAGE_PVP','CLAN_CHALLENGE','CLAN_BATTLE','TOURNAMENT','QUEST','VILLAGE_PROTECTOR','TRAINING') NOT NULL;
ALTER TABLE `BattleHistory` MODIFY COLUMN `battleType` enum('ARENA','COMBAT','SPARRING','KAGE_AI','KAGE_PVP','CLAN_CHALLENGE','CLAN_BATTLE','TOURNAMENT','QUEST','VILLAGE_PROTECTOR','TRAINING');
ALTER TABLE `DataBattleAction` MODIFY COLUMN `battleType` enum('ARENA','COMBAT','SPARRING','KAGE_AI','KAGE_PVP','CLAN_CHALLENGE','CLAN_BATTLE','TOURNAMENT','QUEST','VILLAGE_PROTECTOR','TRAINING') NOT NULL;
ALTER TABLE `UserRequest` MODIFY COLUMN `type` enum('SPAR','ALLIANCE','SURRENDER','SENSEI','ANBU','CLAN','MARRIAGE','KAGE') NOT NULL;
ALTER TABLE `Village` ADD `openForChallenges` boolean DEFAULT true NOT NULL;
ALTER TABLE `Village` ADD `openForChallengesAt` datetime(3) DEFAULT (CURRENT_TIMESTAMP(3)) NOT NULL;