ALTER TABLE `Jutsu` MODIFY COLUMN `requiredRank` enum('STUDENT','GENIN','CHUNIN','JONIN','ELITE JONIN','ELDER','NONE') NOT NULL;
UPDATE UserData SET `rank` = 'JONIN' WHERE `rank` = 'COMMANDER';
ALTER TABLE `UserData` MODIFY COLUMN `rank` enum('STUDENT','GENIN','CHUNIN','JONIN','ELITE JONIN','ELDER','NONE') NOT NULL DEFAULT 'STUDENT';