ALTER TABLE `UserData` ADD `rankedLp` INT DEFAULT 150 NOT NULL;
ALTER TABLE `BattleHistory` MODIFY COLUMN `battleType` ENUM('ARENA', 'COMBAT', 'SPARRING', 'KAGE_AI', 'KAGE_PVP', 'CLAN_CHALLENGE', 'CLAN_BATTLE', 'TOURNAMENT', 'QUEST', 'VILLAGE_PROTECTOR', 'TRAINING', 'RANKED') NOT NULL; 
CREATE TABLE RankedPvpQueue (
  id varchar(191) NOT NULL,
  userId varchar(191) NOT NULL,
  rankedLp int NOT NULL,
  createdAt datetime(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP(3)),
  CONSTRAINT RankedPvpQueue_id PRIMARY KEY(id)
);
CREATE INDEX RankedPvpQueue_userId_idx ON RankedPvpQueue (userId);
CREATE INDEX RankedPvpQueue_rankedLp_idx ON RankedPvpQueue (rankedLp);
ALTER TABLE RankedPvpQueue ADD COLUMN queueStartTime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Battle MODIFY COLUMN battleType ENUM('ARENA', 'COMBAT', 'SPARRING', 'KAGE_AI', 'KAGE_PVP', 'CLAN_CHALLENGE', 'CLAN_BATTLE', 'TOURNAMENT', 'QUEST', 'VILLAGE_PROTECTOR', 'TRAINING', 'RANKED') NOT NULL;
ALTER TABLE DataBattleAction MODIFY COLUMN battleType ENUM('ARENA', 'COMBAT', 'SPARRING', 'KAGE_AI', 'KAGE_PVP', 'CLAN_CHALLENGE', 'CLAN_BATTLE', 'TOURNAMENT', 'QUEST', 'VILLAGE_PROTECTOR', 'TRAINING', 'RANKED') NOT NULL;
