ALTER TABLE `UserData` ADD COLUMN `homeType` enum('NONE','ONE_BED_APARTMENT','STUDIO_APARTMENT','TWO_BED_HOUSE','TOWN_HOUSE','SMALL_MANSION','SMALL_ESTATE','LARGE_ESTATE') NOT NULL DEFAULT 'NONE';
ALTER TABLE UserData ADD COLUMN homeStoredItems JSON NOT NULL;
