-- AlterTable
ALTER TABLE `Item` ADD COLUMN `destroyOnUse` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `type` ENUM('WEAPON', 'CONSUMABLE', 'ARMOR', 'ACCESSORY', 'MATERIAL', 'EVENT', 'OTHER') NOT NULL;
