-- AlterTable
ALTER TABLE `Item` MODIFY `weaponType` ENUM('STAFF', 'AXE', 'FIST_WEAPON', 'SHURIKEN', 'SICKLE', 'DAGGER', 'SWORD', 'POLEARM', 'FLAIL', 'CHAIN', 'FAN', 'BOW') NOT NULL;

-- AlterTable
ALTER TABLE `Jutsu` MODIFY `jutsuWeapon` ENUM('STAFF', 'AXE', 'FIST_WEAPON', 'SHURIKEN', 'SICKLE', 'DAGGER', 'SWORD', 'POLEARM', 'FLAIL', 'CHAIN', 'FAN', 'BOW') NULL;
