name: build-test
on: pull_request
jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: install dependencies
        run: bun install
        working-directory: ./app
      - name: run tests
        run: bun test
        working-directory: ./app
      - name: run build
        run: bun run build
        working-directory: ./app
    env:
      NEXT_PUBLIC_PUSHER_APP_KEY: ${{ secrets.NEXT_PUBLIC_PUSHER_APP_KEY }}
      NEXT_PUBLIC_PUSHER_APP_CLUSTER: ${{ secrets.NEXT_PUBLIC_PUSHER_APP_CLUSTER }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
      PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
      PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
      DATABASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
      CAPTCHA_SALT: ${{ secrets.CAPTCHA_SALT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
